### PR TITLE
fix: won't build with rustc 1.75

### LINKED ISSUE #41: won't build with rustc 1.75
I get the following errors when trying to build under rustc 1.75:

~/dht-crawler$ cargo build
   Compiling krpc_encoding v0.1.0 (/home/jason/dht-crawler/packages/krpc_encoding)
error[E0432]: unresolved import `thiserror`
   --> packages/krpc_encoding/src/errors.rs:22:17
    |
22  | #[derive(Debug, Error)]
    |                 ^^^^^ no `ThiserrorProvide` in `__private`
    |
note: found an item that was configured out
   --> /home/jason/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-1.0.38/src/lib.rs:253:29
    |
253 |     pub use crate::provide::ThiserrorProvide;
    |                             ^^^^^^^^^^^^^^^^
    = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `Demand` in module `std::any`
  --> packages/krpc_encoding/src/errors.rs:22:17
   |
22 | #[derive(Debug, Error)]
   |                 ^^^^^ not found in `std::any`
   |
   = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> packages/krpc_encoding/src/lib.rs:1:12
  |
1 | #![feature(error_generic_member_access, provide_any)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> packages/krpc_encoding/src/lib.rs:1:41
  |
1 | #![feature(error_generic_member_access, provide_any)]
  |                                         ^^^^^^^^^^^

error[E0635]: unknown feature `provide_any`
 --> packages/krpc_encoding/src/lib.rs:1:41
  |
1 | #![feature(error_generic_member_access, provide_any)]
  |                                         ^^^^^^^^^^^

error[E0599]: no method named `thiserror_provide` found for enum `errors::ErrorKind` in the current scope
  --> packages/krpc_encoding/src/errors.rs:26:5
   |
6  | pub enum ErrorKind {
   | ------------------ method `thiserror_provide` not found for this enum
...
26 |     inner: ErrorKind,
   |     ^^^^^ method not found in `ErrorKind`

Some errors have detailed explanations: E0412, E0432, E0554, E0599, E0635.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `krpc_encoding` (lib) due to 6 previous errors

---

I know next to nothing about rust, but it seems like the "thiserror" functionality got deprecated or removed at some point.

### PR DESCRIPTION
**Pull request by webbrain-one**
Closes #41

### CODE REVIEW

**Comment by jduerstock** [comment]
@webbrain-one You did notice that all checks have failed, yes?
